
import * as React from 'react';
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogContentText from '@mui/material/DialogContentText';
import DialogTitle from '@mui/material/DialogTitle';
import Box from '@mui/material/Box';

// Define the data structure (duplicated here for prop type usage, ideally shared)
export interface DictionaryEntry {
    id: number;
    word: string;
    meaning: string;
    pronunciation: string;
    date: string;
}

interface AddEntryModalProps {
    open: boolean;
    handleClose: () => void;
    onSave: (entry: Omit<DictionaryEntry, 'id'> | DictionaryEntry) => void;
    initialData?: DictionaryEntry | null;
}

export default function AddEntryModal({ open, handleClose, onSave, initialData }: AddEntryModalProps) {
    const [word, setWord] = React.useState('');
    const [meaning, setMeaning] = React.useState('');
    const [pronunciation, setPronunciation] = React.useState('');
    const [date, setDate] = React.useState('');

    React.useEffect(() => {
        if (open) {
            if (initialData) {
                setWord(initialData.word);
                setMeaning(initialData.meaning);
                setPronunciation(initialData.pronunciation);
                setDate(initialData.date);
            } else {
                setWord('');
                setMeaning('');
                setPronunciation('');
                // Default to today's date in YYYY-MM-DD format
                setDate(new Date().toISOString().split('T')[0]);
            }
        }
    }, [initialData, open]);

    const handleSave = () => {
        // Construct the entry object
        const entryData = {
            word,
            meaning,
            pronunciation,
            date,
        };

        if (initialData) {
            // If editing, preserve the ID
            onSave({ ...entryData, id: initialData.id });
        } else {
            // If adding, ID will be generated by the parent
            onSave(entryData);
        }

        handleClose();
    };

    return (
        <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
            <DialogTitle>{initialData ? 'Edit Entry' : 'Add New Entry'}</DialogTitle>
            <DialogContent>
                <DialogContentText sx={{ mb: 2 }}>
                    {initialData
                        ? 'Update the dictionary entry details below.'
                        : 'To add a new word to the dictionary, please fill in all the requisite information below.'}
                </DialogContentText>
                <Box
                    component="form"
                    sx={{
                        display: 'flex',
                        flexDirection: 'column',
                        gap: 2,
                    }}
                    noValidate
                    autoComplete="off"
                >
                    <TextField
                        autoFocus
                        margin="dense"
                        id="word"
                        label="Word"
                        type="text"
                        fullWidth
                        variant="outlined"
                        required
                        value={word}
                        onChange={(e) => setWord(e.target.value)}
                    />
                    <TextField
                        margin="dense"
                        id="meaning"
                        label="Meaning"
                        type="text"
                        fullWidth
                        variant="outlined"
                        multiline
                        rows={3}
                        required
                        value={meaning}
                        onChange={(e) => setMeaning(e.target.value)}
                    />
                    <TextField
                        margin="dense"
                        id="pronunciation"
                        label="Pronunciation"
                        type="text"
                        fullWidth
                        variant="outlined"
                        placeholder="/.../"
                        required
                        value={pronunciation}
                        onChange={(e) => setPronunciation(e.target.value)}
                    />
                    <TextField
                        margin="dense"
                        id="date"
                        label="Date Added"
                        type="date"
                        fullWidth
                        variant="outlined"
                        InputLabelProps={{
                            shrink: true,
                        }}
                        required
                        value={date}
                        onChange={(e) => setDate(e.target.value)}
                    />
                </Box>
            </DialogContent>
            <DialogActions>
                <Button onClick={handleClose} color="inherit">Cancel</Button>
                <Button onClick={handleSave} variant="contained" color="primary">
                    {initialData ? 'Save Changes' : 'Add Entry'}
                </Button>
            </DialogActions>
        </Dialog>
    );
}
